name: PDF to Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pdf2image Pillow

      - name: Install poppler
        run: |
          sudo apt-get install poppler-utils

      - name: Run script
        run: |
          python test.py

      - name: Upload images to GitHub (optional)
        uses: actions/upload-artifact@v3
        with:
          name: output-images
          path: /tmp/output_images
